import { writeFileSync } from 'node:fs'
import { join } from 'node:path'

import { listComponents } from './list-components.mjs'

const srcDir = join(import.meta.dirname, '../src')
const names = listComponents(srcDir)
const lines = [
	'// AUTO-GENERATED by scripts/generate-index.mjs — do not edit by hand.',
	...names.map((name) => `export * from './components/${name}/index.js'`),
	"export { cn } from './lib/cn.js'",
	'',
]

writeFileSync(join(srcDir, 'index.ts'), lines.join('\n'))
